/**
 * Vocabulary / lesson types.
 *
 * Ported from fina `types/vocabulary.ts` verbatim, minus the React-Native
 * screen-prop types (`FlashcardScreenProps`, `FlashCardProps`,
 * `FlashcardGestureState`) which have no web equivalent.
 */

export interface VocabularyWord {
  id: string;
  title_id: number;
  word: string;
  definition: string;
  example: string;
  pronunciation?: string;
  difficulty: 'easy' | 'medium' | 'hard';
  category: string;
  partOfSpeech?:
    | 'noun'
    | 'verb'
    | 'adjective'
    | 'adverb'
    | 'preposition'
    | 'conjunction'
    | 'interjection';
  translation?: {
    russian: string;
    spanish: string;
  };
  audioURL: string | null;
  audioGeneratedAt?: string; // ISO timestamp when audio was generated
}

export interface Lesson {
  id: number | string; // Support both integer IDs (predefined) and UUID strings (generated lessons)
  title: string;
  description: string;
  wordsCount: number;
  duration: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  completed: boolean;
  emoji: string;
  vocabularyWords: VocabularyWord[];
  supabaseId?: string; // UUID from generated_lessons table (for deletion)
  isUserGenerated?: boolean; // Flag for user-created lessons (shows badge)
}

/**
 * Lesson Progress
 * Tracks user's progress through a vocabulary lesson
 * Stored in Supabase lesson_progress table
 */
export interface LessonProgress {
  id?: string; // UUID, optional for new records (auto-generated by Supabase)
  user_id?: string; // UUID, references auth.users (added for Supabase)
  lessonId: number | string; // Lesson identifier - string for generated lessons, number for predefined
  completedWords: string[]; // Array of word IDs user has learned
  currentWordIndex: number; // Index of current flashcard (for resuming)
  timeSpent: number; // Total seconds spent on lesson
  accuracy: number; // Percentage of correct answers (0-100)
  lastAccessed: Date | string; // Date object in app, ISO string in DB
  isCompleted: boolean; // Whether user finished all words
  created_at?: string; // ISO timestamp (added for Supabase)
  updated_at?: string; // ISO timestamp (added for Supabase)
}

export interface UserProfile {
  id: string;
  email: string;
  display_name?: string | null; // User's display name (editable in settings)
  user_level:
    | 'beginner'
    | 'elementary'
    | 'intermediate'
    | 'upper_intermediate'
    | 'advanced'
    | 'proficient';
  current_streak: number;
  words_learned: number;
  accuracy: number;
  last_conversation_date?: string | null; // ISO date string for last conversation
  weekly_activity?: string | null; // JSON string of boolean array [Sun, Mon, Tue, Wed, Thu, Fri, Sat]
  target_language?: string | null; // Language the user wants to learn
  learning_motivation?: string | null; // Why the user wants to learn English
  daily_goal_minutes?: number | null; // Daily learning time goal in minutes
  study_plan_completed_days?: string | null; // JSON array of completed day numbers e.g. "[1,2,3]"
  study_plan_start_date?: string | null; // ISO date when the 30-day plan started
  created_at: string;
  updated_at: string;
}

export type DifficultyLevel = 'Beginner' | 'Intermediate' | 'Advanced';
export type WordDifficulty = 'easy' | 'medium' | 'hard';

/**
 * Favorite Word
 * Represents a word bookmarked by the user for quick review
 * Stored in Supabase favorite_words table
 */
export interface FavoriteWord {
  id: string; // UUID
  user_id: string;
  word_id: string;
  word_data: VocabularyWord; // Full word object for easy display
  created_at: string;
}

/**
 * Learning Statistics
 * Aggregated statistics for user learning progress
 * Computed from Supabase tables
 */
export interface LearningStats {
  totalLessonsCompleted: number;
  favoriteWordsCount: number;
}

/**
 * Generated Lesson
 * Represents an AI-generated lesson stored in Supabase
 * Stored in generated_lessons table
 */
export interface GeneratedLesson {
  id: string; // UUID
  user_id: string;
  lesson_data: Lesson; // Full lesson object with vocabularyWords
  topic: string;
  difficulty: string;
  created_at: string;
}

/**
 * Generated Lessons Statistics
 * Statistics about user's AI-generated lessons
 */
export interface GeneratedLessonsStats {
  totalLessons: number; // Total generated lessons count
  totalWords: number; // Sum of all words in generated lessons
  recentLessons: number; // Lessons created in last 7 days
}

/**
 * Onboarding Step
 * Represents a single step in the onboarding flow
 */
export type OnboardingStep = 'language' | 'level' | 'motivation' | 'goal' | 'setup';

/**
 * Onboarding Data
 * Collected data from the onboarding flow
 */
export interface OnboardingData {
  targetLanguage: string;
  userLevel: UserProfile['user_level'];
  learningMotivation: string;
  dailyGoalMinutes: number;
}
